### ISSUE TITLE
Pandas has deprecated NaTType class, used in rough_heuristic_pd_column_type_check function.

### ISSUE THREAD

**Issue by AnthonyCody** [moj-analytical-services/datacleaningutils#6]
Recently reinstalled pandas, now using pandas v0.23.4 (released: 3rd Aug '18) over whatever (v0.?) legacy version was on my Mac/virtual machine.

I now get the following error when calling `rough_heuristic_pd_column_type_check` function:

> .../datacleaningutils/data_types.py", line 25, in rough_heuristic_pd_column_type_check
>     "date": {datetime.date, type(None), pd._libs.tslib.NaTType}
> AttributeError: module 'pandas._libs.tslib' has no attribute 'NaTType'

https://github.com/moj-analytical-services/datacleaningutils/blob/6337da7822df57b9986f78d5111584f34c93a976/datacleaningutils/data_types.py#L25

pandas changelog (http://pandas.pydata.org/pandas-docs/stable/whatsnew.html?highlight=rolling_mean#modules-privacy-has-changed) has the following entry for v0.20.1 (May 5, 2017):
> The type import pandas.tslib.NaTType is deprecated and can be replaced by using type(pandas.NaT) (GH16146)

Pandas <0.20.1 tslib.pyx contains 
> class NaTType(_NaT):

(Latest) pandas 0.23.4 does not.

**Comment by AnthonyCody** [comment]
I'm now using an earlier version of pandas 0.20.1; the last supported pandas 0.20.1 distro (https://pypi.org/project/pandas/0.20.1/#files) was for MacOS 10.1n - it flunks installing on my current 10.14. 

I've gotten around this by building a copy from the GitHub source (https://github.com/pandas-dev/pandas/releases/tag/v0.20.1), Fortunately, this still works in Python 3.7.

`datacleaningutils` now works for me, but this isn't something I'd want a new user to have to do.
